apiVersion: v1
kind: Pod
metadata:
  name: huge-resource-pod
spec:
  containers:
  - name: container-with-huge-resource
    image: nginx:latest
    resources:
      limits:
        memory: "512G"
        cpu: "1000"
      requests:
        memory: "128G"
        cpu: "500"