apiVersion: v1
kind: Pod
metadata:
  name: resource-pod
spec:
  containers:
  - name: container-with-recouse
    image: nginx:latest
    resources:
      limits:
        memory: "128M"
        cpu: "1"
      requests:
        memory: "64M"
        cpu: "0.5"