apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
  - name: first-container
    image: nginx:latest
  - name: second-container
    image: ubuntu:latest
    command: ["/bin/bash", "-ec", "while : ; do echo '.'; sleep 5 ; done"]
